INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('
	
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('23CEC_MH','23 CIA. ENG COMBATE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('3RCG_T','3º REG.CAVAL.GUARDA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('ADABBA_C','ADAB BA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('ANEEL_EV','ANEEL','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('APMBBSP_A','APMBB_SP','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BAGAL_EV','BASE AÉREA DO GALEÃO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BASEAER_G','HOMOL. BASE AÉREA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BASEAERE_','HOMOL. BASE AÉREA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BASEAPLO_','BASE APOIO LOGISTICO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BASP_T','BASE AÉREA DE SP','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BATCHOQ_A','BATALHAO CHOQUE SP','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADIPRH','DEPÓS. IPELÂNDIA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADM','BRGS ADMINISTRAÇÃO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADM_','BRGS ADMINISTRAÇÃO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADMC','BRGS ADM LIC CARTORI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADMC','BRGS ADM COMPRAS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADMC','BRGS ADM CONTAB','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADMC','BRGS ADM LIC CORREIO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADMDI','BRGS ADM LIC DILIGEN','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADMFI','BRGS ADM FINANCEIRO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADMIPE','DEPÓS. IPELÂNDIA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADMLI','BRGS ADM LICITAÇÕES','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADMM','BRGS ADM LIC MOTOBOY','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADMNF','BRGS ADM NF','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADMOP','BRGS ADM OPERAÇÕES','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADMPG','DEPÓS. PRAIA GRANDE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADMRH','BRGS ADM RH','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADMS','DEPÓS. SUZANO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADMTI','BRGS ADM TI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADMTR','BRGS ADM TRANSPORTE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADPG_','DEPÓS. PRAIA GRANDE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADPG_','DEPÓS. PRAIA GRANDE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSADPGR','DEPÓS. PRAIA GRANDE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSCOBA','BRGS UEN COBERTU ADM','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSCOBC','BRGS UEN COBERTU CON','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSCOBFIN','BRGS UEN COBERTU FIN','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSCOBNF','BRGS UEN COBERTU NF','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSCOBRH','BRGS UEN COBERTU RH','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSCOBTI','BRGS UEN COBERTU TI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSCONTA','BRGS CONTAINER','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSESTAD','BRGS UEN ESTANDE ADM','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSESTCO','BRGS UEN ESTANDE CON','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSESTFIN','BRGS UEN ESTANDE FIN','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSESTNF','BRGS UEN ESTANDE NF','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSESTRH','BRGS UEN ESTANDE RH','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSESTTI','BRGS UEN ESTANDE TI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSLIC','BRGS LICITAÇÕES','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSLICCAR','BRGS LICIT CARTORIO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSLICCOR','BRGS LICIT CORREIOS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSLICDIL','BRGS LICIT DILIGENCI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSLICMOT','BRGS LICIT MOTOBOY','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSLOGA','BRGS UEN LOGISTI ADM','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSLOGC','BRGS UEN LOGISTI CON','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSLOGFIN','BRGS UEN LOGISTI FIN','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSLOGNF','BRGS UEN LOGISTI NF','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSLOGRH','BRGS UEN LOGISTI RH','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSLOGTI','BRGS UEN LOGISTI TI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSMHAD','BRGS UEN MOD HAB ADM','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSMHCON','BRGS UEN MOD HAB CON','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('B RGSM H FIN','BRGS UEN MOD HAB FIN','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('B RGSM H NF','BRGS UEN MOD HAB NF','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSMHRH','BRGS UEN MOD HAB RH','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSMHTI','BRGS UEN MOD HAB TI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSOPE','BRGS OPERAÇÕES','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSOPECO','BRGS OPE CORREIOS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSOPEDIL','BRGS OPE DILIGÊNCIAS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSOPEMO','BRGS OPE MOTOBOY','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSTUBAD','BRGS UEN TUBULAR ADM','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSTUBCO','BRGS UEN TUBULAR CON','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSTUBFIN','BRGS UEN TUBULAR FIN','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSTUBNF','BRGS UEN TUBULAR NF','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSTUBRH','BRGS UEN TUBULAR RH','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('BRGSTUBTI','BRGS UEN TUBULAR TI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('CCUSTO01','CENTRO DE CUSTO XX','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('CCUSTO07','CENTRO DE CUSTO 07','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('CEFETRJ_E','CEFET-RJ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('COMANCHE_','COMENCHE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('COMARA_C','COMIS.AEROP.AMAZONIC','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('COMARA_M','COMARA AMAZÔN IA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('COMARJ_TO','COMANDO MARINHA RJ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('COMENCH_G','COMENCHE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('COMENCHE_','COMENCHE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('CORREIO_MH','CORREIOS - BA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('CPTM_G','CPTM SP','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('CTIRA_MH','CTI RENATO ARCHER','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('DEFCIRJ_ET','DEFESA CIVIL RJ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('DEFCIVRJ_C','DEFESA CIVIL RJ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('DETRANPE_E','DETRAN PE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('DETRANRJ_','DETRAN RJ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('DIVISORI_E','DIVISORIAS POÁ-DECIO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('ELETRON_C','ELETRONUCL.ANGRA 1','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('ELETRON_G','ELETRON ANGRA 1 E 2','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('ELETRON_M','ELETRONUCLE MOD.HAB.','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('ELETRON_T2','ELETRONUCL.CNAAA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('ELETRON_T3','ELETRONUCL.ANGRA 2','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('ELETRON U_C','ELETRONUCL.ANGRA 1','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('ELETRONU_','ELETRONUCL.ANGRA 2','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('ELETRONU_','ELETRONUCL.ANGRA 1','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('ELETRONU_T','ELETRONUCL.ANGRA 1','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('ELETROSU_C','ELETROSUL','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('ELETROSU_','ELETROSUL','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('ESAR_A','ESCOLA SARGENTOS MG','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FAETECRJ_E','FAETEC RJ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FAETECRJ_G','FAETEC RJ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FESTJUVE_E','FESTIVAL JUVENTUDE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FESTNATA_E','FESTIVAL NATALINO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FFLOWER_C','FUN FLOWER SHELL','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FIOCRUZ_C','FIOCRUZ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FIOCRUZ_E','FIOCRUZ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FIOCRUZ_GO','FIOCRUZ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FONTESAP_','PM SANTOS FONTE SAPO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONADM','FRONT ADMINISTRAÇÃO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONADM_G','FRONT ADMINISTRAÇÃO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONADMC','FRONT ADM CONTAB','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONADMFIN','FRONT ADM FINANCEIRO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONADMNF','FRONT ADM NF','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONADMRH','FRONT ADM RH','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONADMTI','FRONT ADM TI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONCOBAD','FRON UEN COBERTU ADM','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONCOBCO','FRON UEN COBERTU CON','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONCOBFIN','FRON UEN COBERTU FIN','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONCOBNF','FRON UEN COBERTU NF','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONCOBRH','FRON UEN COBERTU RH','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONCOBTI','FRON UEN COBERTU TI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONESTAD','FRON UEN ESTANDE ADM','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONESTCO','FRON UEN ESTANDE CON','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONESTFIN','FRON UEN ESTANDE FIN','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONESTNF','FRON UEN ESTANDE NF','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONESTRH','FRON UEN ESTANDE RH','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONESTTI','FRON UEN ESTANDE TI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONLIC','FRONT LICITAÇÕES','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONLICCAR','FRONT LICIT CARTORIO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONLICCOR','FRONT LICIT CORREIOS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRON L ICD IL','FRONT LICIT DILIGEN','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONLICMOT','FRONT LICIT MOTOBOY','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONLOGAD','FRON UEN LOGISTI ADM','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONLOGCO','FRON UEN LOGISTI CON','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONLOGFIN','FRON UEN LOGISTI FIN','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONLOGNF','FRON UEN LOGISTI NF','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONLOGRH','FRON UEN LOGISTI RH','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONLOGTI','FRON UEN LOGISTI TI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONMHADM','FRON UEN MOD HAB ADM','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONMHCON','FRON UEN MOD HAB CON','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRON M H F IN','FRON UEN MOD HAB FIN','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRON M H N F','FRON UEN MOD HAB NF','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONMHRH','FRON UEN MOD HAB RH','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONMHTI','FRON UEN MOD HAB TI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONOPE','FRONT OPERAÇÕES','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONOPECO','FRONT OPE CORREIOS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONOP ED IL','FRONT OPE DILIGÊNCIA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONOPEMO','FRONT OPE MOTOBOY','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONTUBAD','FRON UEN TUBULAR ADM','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONTUBCO','FRON UEN TUBULAR CON','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONTUBFIN','FRON UEN TUBULAR FIN','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONTUBNF','FRON UEN TUBULAR NF','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONTUBRH','FRON UEN TUBULAR RH','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FRONTUBTI','FRON UEN TUBULAR TI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('FURNAS_C','FURNAS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('GALPAO_C','GALPAO POÁ-DECIO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('GHC_C','GRUPO GHC','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('G IAASJC_PT','GIA SJCAMPOS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('HCPA-RS_E','HCPA-RS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('HEMOCESP_','HEMOCENTRO SP','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('IBIRAPUE_E','IBIRAPUERA SP','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('IFECTCAT_C','MOD. HAB. IFECTC','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('IFECTCAT_E','Inst.Fed.Educ.Catar.','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('ILHABELA_E','ILHABELA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('IME_C','IME - FORMATURA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('IME_GO','IME - FORMATURA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('IME_T','IME - FORMATURA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('INFRAER_M H','INFRAE SANTOS DUMONT','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('INFRAER_PE','INFRAE AEROP. RECIFE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('INFRAER_RJ','INFRAE SANTOS DUMONT','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('ITESP_E','ITESP','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('JDBOTANI_C','JD BOTANICO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('MANDAQU_','SAUDE-SP MANDAQUI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('MIRACATU_T','RODEIO MIRACATU','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('MJFUNAI_C','MIN. JUSTICA-FUNAI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('MUHIFCO_EQ','MUS.HIST.FOR.COPAC.','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('MUHIFCO_G','MUS.HIST.FOR.CAPAC.','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('MUHIFCOP_C','MUS.HIST.FOR.COPAC.','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('MUHIFCOP_T','MUS.HIST.FOR.CAPAC.','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PALCOX9_C','PALCO X-9','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PALCOX9_E','PALCO X-9','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PFMG_GO','POL. FED. REG. MG','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PFMG_MH','POL. FED. REG. MG','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PFPE_CGP','POL. FED. REG. PE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PFPE_PL','POL. FED. REG. PE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PLJEFERSON','P.L. JEFERSON','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PLRITA','P.L. RITA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PM ARUJA_P','PM ARUJÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMAMERIC_P','PM AMERICANA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMAMERIC_T','PM AMERICANA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMARUJA_B','PM ARUJÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMARUJA_C','PM ARUJÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMARUJA_E','PM ARUJÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMARUJA_F','PM ARUJÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMARUJA_G','PM ARUJÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMARUJA_H','PM ARUJÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMARUJA_M','PM ARUJÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMARUJA_MI','PM ARUJÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMARUJA_P','PM ARUJÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMARUJA_P','PM ARUJÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMARUJA_P','PM ARUJÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMARUJA_R','PM ARUJÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMARUJA_S','PM ARUJÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMARUJA_S','PM ARUJÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMARUJA_T','PM ARUJÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMBERTIO_E','PM BERTIOGA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMCAMPI_G','PM CAMPINAS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('P MCAM P IN_C','PM CAMPINAS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('P MCAM P IN_F','PM CAMPINAS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('P MCAM P IN_P','PM CAMPINAS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMCAPIV_EV','PM CAPIVARI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMCARAG_E','PM CARAGUATATUBA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMCOTIA_A','PM COTIA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMDIADEM_S','PM DIADEMA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMGUARA_E','PM GUARAREMA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMGUARAR_','PM GUARAREMA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMGUARAR_','PM GUARAREMA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMGUARU_C','PM GUARULHOS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMGUARU_G','PM GUARULHOS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMGUARU_M','PM GUARULHOS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PM ILHAB_S I','PM ILHABELA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMILHABE_A','PM ILHABELA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMILHABE_T','PM ILHABELA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMJABOT_B','PM JABOTICABAL','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMJABOT_TE','PM JABOTICABAL','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMJABOTI_E','PM JABOTICABAL','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMJABOTI_G','PM JABOTICABAL','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMJANDI_GO','PM JANDIRA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMMOGI_EV','PM MOGI DAS CRUZES','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMNHAMB_E','PM NOVO HAMBURGO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMPARATY_','PM PARATY','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMPELOTA_','PM PELOTAS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMPIRACI_P','PM PIRACICABA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMPIRACI_T','PM PIRACICABA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMPOA_E','PM POÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMPOA_ES','PM POÁ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMRJ_MH','PM RIO DE JANEIRO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMSANTA_G','PM SANTANA PARNAIBA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMSANTA_P','PM SANTANA PARNAIBA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMSANTO_B','PM SANTOS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMSANTO_PI','PM SANTOS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMSANTOS_','PM SANTOS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMSANTOS_','PM SANTOS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMSANTOS_','PM SANTOS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMSANTOS_','PM SANTOS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMSANTOS_','PM SANTOS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMSP_CT','PM SP TURISMO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMSP_GR','PM SÃO PAULO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMSP_VE','PM SP TURISMO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMSP_VMA_','PM SP MEIO AMBIENTE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMSUZAN_E','PM SUZANO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMTAUBAT_','PM TAUBATE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMTRESRI_E','PM TRES RIOS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMURUGU_E','PM URUGUAIANA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMURUGU_G','PM URUGUAIANA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMVITOR_G','PM VITORIA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PM VITORI_C','PM VITORIA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('PMVITORI_E','PM VITORIA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SABESP_G','SABESP GERADOR VR','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SABESPCJ_','SABESP CAPIV.-JUND.','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SABESPFR_','SABESP FRANCA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SEASDH_MH','SECR. ASS.SOCIAL RJ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SECSAUPE_','Secr.Saúde Est. PE','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SENACSP_E','SENAC SP','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SENAI-SP_C','SENAI SP','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SENAI-SP_E','SENAI SP','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SENAI-SP_G','SENAI SP','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SESCPR_G','SESC PR','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SESCRJ_C','SESC RJ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SESCRJ_E','SESC RJ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SESCRJ_GO','SESC RJ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SESCRJ_t','SESC RJ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SESCRJ_TRA','SESC RJ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SESCSP_P','SESC SP','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SESCSPCA_','SESC SP CAMPINAS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SESCSPCA_','SESC SP CAMPINAS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SESCSPCA_','SESC SP CAMPINAS','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SESI-SP_E','SESI SP','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SPTURIS_C','SP TURISMO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SPTURIS_E','SP TURISMO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SPTURIS_GO','SP TURISMO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SPTURIS_T','SP TURISMO','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('SSMANDAQ','SECR.SAUDE-MANDAQUI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('T.I.','BRGS ADM TI','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('TRE-BA_EMP','TRE BAHIA','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('UFGD_T','UNIV.FED.GRANDE DOUR','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('UFRRJ_T','UNIV. FED. RURAL RJ','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('UFSCARSP_','UFSCAR SP','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('UFSM_C','UFSM','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('UFSM_GO','UFSM','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('UNFEDABC_','UF ABC','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('U N FE PR_C','UNIV.TEC.FEDERAL PR','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('USP_E','USP_SP','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('USP_G','USP_SP','0');
INSERT INTO CentroCustos (Codigo,Descricao,UnitTest) VALUES ('USP_T','USP_SP','0');
