INSERT INTO Despesas (Descricao, UnitTest) VALUES ('Transferência Bancária', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('Créditos a Receber', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('ALUGUEL', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('CONSERVAÇÃO E LIMPEZA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('ENERGIA ELÉTRICA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('TELEFONE', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('INTERNET', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('ÁGUA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('MANUTENÇÃO E CONSERTO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('CONTABILIDADE', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('CORREIOS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('SEGUROS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('MATERIAL ESCRITORIO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('CONDOMINIO E IPTU', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('CARTORIO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('MULTAS DE TRANSITO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('PROTESTO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('CONSULTORIA JURÍDICA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('CAIXINHA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('SERVIÇOS DE MOTOBOY', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('VISITAS TÉCNICAS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('DESPESAS DE LICITAÇÃO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('SUPERMERCADO - DESPESAS DE', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('PROPAGANDA E MARKETING', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('COMISSÕES', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('VIAGENS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('FRETES', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('ESTADIAS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('COMBUSTIVEIS E LUBRIFICANTES', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('MAO-DE-OBRA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('COMPRAS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('MOTOBOY', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('CPMF', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('IOF', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('TARIFA BANCARIA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('ENCARGOS DE CC', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('ENCARGOS LIS E RECEBIVEIS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('CVL - COMISSAO DE VALOR LIBERADO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('TARIFA LIS RENOVACAO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('TARIFA DE COBRANCA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('TARIFA DE DOC / TED', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('RENOVACAO LIS E RECEBIVEIS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('TARIFA DE ADIANTAMENTO A', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('EMPRÉSTIMO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('EQUIPAMENTOS DE HARDWARE', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('SOFTWARES', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('CURSOS E TREINAMENTOS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('VEÍCULOS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('JORNAIS E REVISTAS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('RRT - REGISTRO DE', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('ACT - ATESTADO CAPACIDADE TÉCNICA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('PAGAMENTO FORNECEDOR', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('MONTAGEM', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('DESMONTAGEM', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('ELÉTRICA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('LOCAÇÃO DE VEÍCULOS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('PINTURA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('REFORMA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('HIDRÁULICA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('SERRALHERIA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('PROVEDOR DE INTERNET', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('CATRACA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('COIFA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('C.A.U. - CONSELHO DE ARQUITETURA E', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('C.R.E.A. - CONSELHO REGIONAL', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('C.R.A. - CONSELHO REGIONAL DE', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('MARCENARIA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('PROJETO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('SALÁRIOS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('FÉRIAS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('13 SALARIO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('SEGURO DE VIDA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('PLANO DE SAÚDE', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('ALIMENTAÇÃO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('CIEE', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('PREVIDENCIA VGBL', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('TRANSPORTE', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('ADIANTAMENTO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('REEMBOLSO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('ASU - EXAMES ADMISSIONAIS /', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('ALIMENTAÇÃO / TRANSPORTE', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('COMBUSTÍVEL', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('COMISSÃO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('CAMPS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('DIARISTA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('HONORÁRIOS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('RESCISAO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('PRODUTOR', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('HOSPEDAGEM / ALIMENTAÇÃO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('METRAGEM', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('PRO LABORE', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('ICMS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('IPI', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('ISS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('PIS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('COFINS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('CSLL', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('IRPJ', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('CONTRIBUICAO SOCIAL', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('ACORDOS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('IPVA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('IMPOSTO SINDICAL', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('TAXA DE LIXO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('IRRF', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('PIS RF', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('COFINS RF', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('CSLL RF', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('TAXA LICENCA DE FUNCIONAMENTO', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('TFE-TAXA DE FISCALIZAÇÃO DE', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('IPTU', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('DARF', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('DAM/SP', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('GARE', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('LICENCIAMENTO VEICULAR', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('DAS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('GPS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('FGTS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('INSS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('GRCS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('PAGAMENTOS A TERCEIROS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('PAGAMENTO DE EMPRESTIMOS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('TRANSFERENCIA CAIXINHA', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('TRANSFERENCIA ENTRE CONTAS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('INSUMOS', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('DOAÇÕES', '0');
INSERT INTO Despesas (Descricao, UnitTest) VALUES ('RECEBIMENTO DE CLIENTES', '0');
